# -*- coding: utf-8 -*-
"""04_extra_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dDgzDcZ9bEkgI5hkpjWAb5b5PR8s1Il
"""

from google.colab import files
uploaded = files.upload()
#upload files from the computer to colab, this is needed to load local dataset into the notebook

# Commented out IPython magic to ensure Python compatibility.

# %run "feature_engineering.py"

df_extra=df.copy()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

numeric_df=df_extra.select_dtypes(include=[np.number])
corr_with_charges=numeric_df.corr()["charges"].sort_values(ascending=False)

print("correlation with charges:")
print(corr_with_charges)

top_corr=corr_with_charges.drop("charges").head(6)


plt.figure(figsize=(8,5))
sns.barplot(x=top_corr.values,y=top_corr.index)
plt.title("top features correlated whth charges ")
plt.xlabel("correlation")
plt.ylabel("features")
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(x="region",y="charges",data=df_extra)
plt.title("charges distribution by region")
plt.show()

"""# **insight — Pairplot Analysis:**

The plot shows the distribution of medical charges (log_charges) against several factors like age, BMI, and number of children.

We see some very high charges around 0.8, indicating rare cases with large expenses.

Age reaches up to 0.3, showing most people are in a medium range without much spread.

Charges_per_BMI (0.2–0.3) shows a clear relationship: higher BMI relative to charges may lead to higher medical costs.

BMI and its interaction with children (BMI_times_children 0.1–0.2) shows a weak effect, but still gives insight about variable interactions.

# **Why this plot is useful:**

Helps see all variables at once and identify which are related to charges.

Shows spread and outliers for each variable.

Allows understanding potential relationships before building any model, especially for interactions between variables.

# insight — Charges by Region(boxplot):

The boxplot shows medical charges in each region. All regions have some outliers. Southwest has the fewest outliers, so charges are more similar there. Southwest and Northwest boxes are short, which means low variation in charges. Northeast box is a bit taller, showing more variation. Southeast has the longest box and the farthest outliers, which means charges vary a lot and some people have very high costs. We chose a scatterplot next to see how other factors like age or BMI affect charges togethe
"""