# -*- coding: utf-8 -*-
"""cleaning_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeE0A6l1rhHSfK-cr6MPrbC8_hIP1yPU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

def load_data():
  csv_path=os.path.join(path,"insurance.csv")
  df=pd.read_csv(csv_path)
  print(df.head())#show first 5 rows so we see what the data looks like
  print(df.shape)# see how many rows and columns we have
  print(df.info())# check types of columns and non-empty counts
  print(df.isnull().sum())# check which columns have missing values
  return df
df_raw=load_data()
print("Path to dataset files:", path)

#function to clean data
def clean_data(df):
    # for text columns, use 'unknown'+ fill missing values
    df["sex"]=df["sex"].fillna("unknown")
    df["smoker"]=df["smoker"].fillna("unknown")
    df["region"]=df["region"].fillna("unknown")
    # for numbers, use median
    df["bmi"]=df["bmi"].fillna(df["bmi"].median())


    # change text columns to category type to save memory and make analysis easier+they have limited repeated values
    df["sex"]=df["sex"].astype("category")
    df["smoker"]=df["smoker"].astype("category")
    df["region"]=df["region"].astype("category")



    print(df.duplicated().sum())#check duplicates
    # remove duplicate rows because repeated rows can affect the analysis and give wrong results
    df=df.drop_duplicates()
    print(df.shape[0])# show number of rows left after removing duplicates to check changes



    # look at outliers in the charges column
    plt.figure(figsize=(8,5)) # create a figure of size 8x5 inches for the plot
    sns.boxplot(x=df["charges"])# draw a boxplot of the 'charges' column to see how charges look and check if there are very high value
    plt.title("Boxplot of Charges Before Capping")# add a title to the plot
    plt.show() # show the plot on the screen
    # i see some really high charges that are far from most value(outliers)



    # cap values bigger than 99th percentile to reduce the effect of extreme outliers on analysis
    q99 = df['charges'].quantile(0.99)
    df.loc[df['charges'] > q99, 'charges'] = q99


    # check the 'charges' column again after capping
    plt.figure(figsize=(8,5))
    sns.boxplot(x=df['charges'])
    plt.title("Boxplot of Charges After Capping")
    plt.show()
    # after capping, the really high charges are smaller now the chart looks better


    assert df['charges'].isnull().sum() == 0 # no missing values left
    assert (df['charges'] > 0).all()  # all charges are positive
    assert df.shape[1] == 7 # make sure we have 7 columns
    print("\n we finally finished clean the dataa")
    return df

df_raw=load_data()
df=clean_data(df_raw)

df.to_csv("insurance_cleaned.csv",index=False)