# -*- coding: utf-8 -*-
"""eda_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6w3pxlwlSwmjxRJbZLyqlD-l2Oqhc7f
"""

from google.colab import files
uploaded = files.upload()
#upload files from the computer to colab, this is needed to load local dataset into the notebook

#import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from numpy import dot
from numpy.linalg import norm

# Download latest version of the dataset from kaggle and load it into a dataframe
path = kagglehub.dataset_download("mirichoi0218/insurance")

def load_data():
  csv_path=os.path.join(path,"insurance.csv")#build the full path to the csv file
  df=pd.read_csv(csv_path)#read the csv file into a pandas dataframe
  return df
df_raw=load_data()
print("Path to dataset files:", path)#show where the dataset was downloaded

# Commented out IPython magic to ensure Python compatibility.

# %run "feature_engineering.py"

"""# **phase3**"""

df_final=df.copy()  # create a copy of the dataframe to preserve the original data
print(df_final.head())# show first 5 rows to verify the data

#calculate mean charges grouped by age_group
grouped = df_final.groupby("age_group", observed=False)["charges"].mean()
print("mean charges by age group:", grouped)#display mean charges per age group

"""# **grouped summary insight**
- Average medical charges increase in older age groups.  
This suggests that age may be an important factor affecting medical expenses.
"""

#create histograms for numerical features
plt.figure(figsize=(15,4))#set figure size for 3 subplot

plt.subplot(1,3,1)#first subplot
sns.histplot(df_final["age"], kde=True)#plot distribution of age with kde
plt.title("age distribution") #title for age histogram

plt.subplot(1,3,2)#second histogram
sns.histplot(df_final["bmi"], kde=True) # plot distribution of BMI with KDE
plt.title("bmi distribution") # title for BMI histogram

plt.subplot(1,3,3) # third subplot
sns.histplot(df_final["charges"], kde=True)# plot distribution of charges with kde
plt.title("Charges distribution") # title for charges histogram

plt.show()# render all 3 histograms

"""# **histogram insights**


- Age: Most people are young or adult, fewer old people — distribution is slightly skewed to the right.

- bmi: Most values are around normal weight, but some high BMI values stretch the distribution right — right-skewed.

Note: BMI values appear with negative numbers because the feature was standardized (z-score). Negative values mean the BMI is below the dataset average, not that BMI is actually negative.

- charges: Most people have low to medium charges, a few have very high costs strongly right-skewed

Note: Medical charges also appear with negative and positive values because the target variable was standardized during preprocessing. Values below 0 represent charges lower than the dataset average, while values above 0 represent higher-than-average charges.



"""

#boxplot to compare charges between smokers and non-smokers
plt.figure(figsize=(12,5))
sns.boxplot(x="smoker_yes",y="charges",data=df_final)
plt.title("charges by Smoker") # title for boxplot
plt.show() # display the boxplot

"""# **Boxplot insights**

- **Non-smokers (False):** Most charges are below the standardized mean, distribution is narrow, and most people have low costs. There are a few outliers above 0.8, representing a small number of people with higher charges.
- **Smokers (True):** Most charges are above the mean, distribution is wider, and some have very high costs. There are no clear outliers like non-smokers.
- **Reason for the shape:** The box shows the range between the first and third quartiles, and the line inside is the median. If data is concentrated away from the mean or spread out, the box looks long or has few points. For smokers, most charges are above the mean, so the box appears entirely above zero—this doesn’t mean data is missing.
"""

# correlation heatmap
numeric_df = df_final.select_dtypes(include=[np.number])  # select only numeric columns
corr_matrix = numeric_df.corr()  # calculate correlation matrix

# get top 10 features most correlated with charges
top_features = corr_matrix["charges"].abs().sort_values(ascending=False).iloc[1:11].index

plt.figure(figsize=(10,6))
sns.heatmap(df_final[top_features].corr(), annot=True, cmap="coolwarm")  # plot heatmap of correlations
plt.title("top 10 features correlated with charges")  # heatmap title
plt.show()  # display heatmap

"""# **Heatmap insight**

most features are strongly correlated with themselves (diagonal).
Strong correlations between some features:

children and children_per_age: 0.9

bmi and bmi_times_children: 0.68

age and log_charges: 0.55
"""

# scatter plot to see relationship between bmi and charges with additional info
plt.figure(figsize=(8,6))
sns.scatterplot(x="bmi",y="charges",hue="smoker_yes",size="children",data=df_final) # color by smoker, size by number of children
plt.title("bmi vs charges colored by smoker,sized by children ")# scatterplot title
plt.show()# show scatterplot

"""# **scatter plot insight**

Non-smokers (blue) mostly have lower charges around -1 to 0, with point sizes showing number of children. Smokers (orange) generally have higher charges, with some clusters around 0–1 and others around 2–3. Larger points represent people with more children. This shows that smoking is the main factor affecting higher charges, while BMI and number of children have less clear effects but can increase charges for some smokers. Values are standardized, so points higher on the axis mean higher charges, and lower points mean lower charges.
"""

#compute mean and standard diviation manually
charges=df_final["charges"].values

mean_charges=np.sum(charges)/len(charges)#manual mean
std_charges=np.sqrt(np.sum((charges-mean_charges)**2)/len(charges))
print("mean charges:",mean_charges)#why?  to understand central value
print("std charges:",std_charges) #why?  to understand spread

#standardize age manually and compare with sklearn
age=df_final["age"].values
z_age=(age-age.mean())/age.std()#manual zscore
scaler=StandardScaler()#sklearn scaler
age_scaled=scaler.fit_transform(df_final[["age"]]).flatten()#scale age using sklearn
print("max difference between manual z and StandardScaler:", np.max(np.abs(z_age - age_scaled)))#check they are same

# cosine similarity between highest and lowest charge records
featurs_for_cosing=["age","bmi","children","charges"]
high_record=df_final.iloc[df_final["charges"].idxmax()][featurs_for_cosing].values  # highest charges
low_record=df_final.iloc[df_final["charges"].idxmin()][featurs_for_cosing].values# lowest charges
cos_sim=dot(high_record,low_record)/(norm(high_record)*norm(low_record))# compute similarity
print("Cosine similarity between highest and lowest charges records:", cos_sim)  # see how similar high and low records are

# fraction of smokers with high charges
threshold=mean_charges+1.5*std_charges#define high charges
high_charges_fraction=df_final[(df_final["smoker_yes"]==1)&(df_final["charges"]>threshold)].shape[0]/df_final[df_final["smoker_yes"]==1].shape[0]
print("fraction of smokers with charges > 1.5 std above mean:", high_charges_fraction)#see risk group

#regression setup
x=df[["age","bmi","children","sex_male","smoker_yes",
      "charges_per_bmi","children_per_age","bmi_times_children","age_group_ord"]]
y=df["charges"]#target

#split dataet into train/test
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42 )# why? test model on unseen data

#train linear regression model
model=LinearRegression()
model.fit(x_train,y_train)#fit model to training data
y_pred=model.predict(x_test)#predict charges on test data

#evaluate model
mse=mean_squared_error(y_test,y_pred) # measure error
r2=r2_score(y_test,y_pred)# measure fit

print("linear regression performance")
print("mean squared error(mse):",mse)#smaller=better
print("r-squared(r2):",r2)#closer to 1 =better fit

"""# **Dashboard with 4 charts**

"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axs = plt.subplots(2,2,figsize=(12,8))

#violin
# Violin Plot: shows the distribution of BMI and its density, also shows median and quartiles
# Source: "What is a violin plot and how to make a Seaborn violinplot in Python"
# by Kimberly Fessel (YouTube)

sns.violinplot(y="bmi",data=df_final,ax=axs[0,0])
axs[0,0].set_title("violin plot")

#box plot
# Box Plot: shows median, quartiles, and outliers of BMI

sns.boxplot(y="bmi",data=df_final,ax=axs[0,1])
axs[0,1].set_title("box plot")

#histogram
# Histogram: shows how many people have each range of BMI (frequency)

sns.histplot(df_final["bmi"],bins=20,ax=axs[1,0])
axs[1,0].set_title("histogram plot")

#kda plot
# KDE Plot: shows smooth curve of BMI distribution (density)

sns.kdeplot(df_final["bmi"],shade=True,ax=axs[1,1])
axs[1,1].set_title("kde plot")


plt.tight_layout()
plt.show()