# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYJ4H-p9PMMIzxWAoZ7PLX1L3YcSAP3d
"""

from google.colab import files
uploaded = files.upload()
#upload files from the computer to colab, this is needed to load local dataset into the notebook

#import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub

# Download latest version of the dataset from kaggle and load it into a dataframe
path = kagglehub.dataset_download("mirichoi0218/insurance")

def load_data():
  csv_path=os.path.join(path,"insurance.csv")#build the full path to the csv file
  df=pd.read_csv(csv_path)#read the csv file into a pandas dataframe
  return df
df_raw=load_data()
print("Path to dataset files:", path)#show where the dataset was downloaded

# Commented out IPython magic to ensure Python compatibility.
#run the cleaning script to preprocess the data
# %run "cleaning_01.py"

# Feature engineering steps adapted from:
# "Feature Engineering for AI: Transforming Raw Data into Predictions" by IBM Technology


#make a copy of the dataframe to avoid modifying the original
df = df_raw.copy()  # use the dataframe loaded in the notebook

# use the dataframe loaded in the notebook
#reason:preserve the original data in case we need it later
print(df.columns) #check column names to see the initial structure


# one-hot encode "sex"and"smoker" if they exist otherwise notify that dummy columns are already present
if "sex" in df.columns or "smoker" in df.columns:
  df = pd.get_dummies(df, columns=["sex","smoker"], drop_first=True)#convert categorical columns to numbers for modeling
else:
  print("dummy columns already exist") #notify that dummy columns are present


#bin "age"into group first
df["age_group"]=pd.cut(df["age"],bins=[0,25,50,100],labels=["young","adult","old"])#bin age into meaningful groups

#ordinal encode <age_group> for modeling
age_order ={"young":0,"adult":1,"old":2}
df["age_group_ord"]=df["age_group"].map(age_order)#convert age groups into ordinal numbers

#scale numerical columns "bmi" and "charges" using standardscaler
scaler=StandardScaler()
df[["bmi","charges"]]=scaler.fit_transform(df[["bmi","charges"]]) #standardize numerical columns for better model performance

#create domain feature (ratios for better analysus)
df["charges_per_bmi"]=df["charges"]/(df["bmi"]+1e-5) # Create ratio: charges per BMI to capture cost effect
df["children_per_age"]=df["children"]/(df["age"]+1e-5) # Create ratio: children per age to show dependency


#create an interaction feature
df["bmi_times_children"]=df["bmi"]*df["children"]#interaction feature combining BMI and number of children

#log-transform a skewed column
df["log_charges"]=np.log1p(df["charges"])#log-transform skewed charges to reduce skewness


#histogram to compare befor and after log-transform
plt.figure(figsize=(12,5))

#befor log transform
plt.subplot(1,2,1)
sns.histplot(df["charges"],kde=True)
plt.title("befor log transform")#show distribution befor transformation

#after log transform
plt.subplot(1,2,2)
sns.histplot(df["log_charges"],kde=True)
plt.title("after log transform")#show distribution after transformation
plt.show()


#remive highly correlated feature(r > 0.95)to reduce multicollinearity
numeric_df=df.select_dtypes(include=[np.number])
corr_matrix=numeric_df.corr().abs()
upper=corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(bool))
to_drop=[columns for columns in upper .columns if any(upper[columns]>0.95)]
df=df.drop(columns=to_drop)

#display the first rows and columns names and shape of the final dataframe
print(df.head())
print("columns:",df.columns)
print("shape",df.shape)