# -*- coding: utf-8 -*-
"""phase3_data_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jimxdq4Lu6vgH4jbt6aSyvaaQy3dNyy
"""

import pandas as pd
import os
import kagglehub

path = kagglehub.dataset_download("mirichoi0218/insurance")

def load_data():
    csv_path = os.path.join(path, "insurance.csv")
    df = pd.read_csv(csv_path)
    return df

df_raw = load_data()

os.makedirs("raw", exist_ok=True)
os.makedirs("cleaned", exist_ok=True)

df_raw.to_csv("raw/insurance.csv", index=False)

df_clean = df_raw.copy()
df_clean = df_clean.dropna()

df_clean.to_csv("cleaned/insurance_cleaned.csv", index=False)

packages = ["pandas", "numpy", "matplotlib", "seaborn", "scikit-learn", "kagglehub"]

with open("requirements.txt", "w") as f:
    for pkg in packages:
        f.write(pkg + "\n")

import pandas as pd
df_clean = pd.read_csv("cleaned/insurance_cleaned.csv")